import './style.css';

const icons = { brain:'✦', home:'⌂', mission:'◈', agents:'♢', tools:'⊞', memory:'◉', settings:'⚙', send:'➤', mic:'◌', search:'⌕', arrow:'↗', check:'✓', play:'▶', pause:'Ⅱ', plus:'＋', dots:'•••', shield:'♢', globe:'◎', code:'⌘', eye:'◉' };
const state = { active:'Mission Control', running:false, voice:false, query:'', messages:[{role:'ai', text:'Good morning. I’m Aegis, your autonomous work OS. Tell me what you want to make happen — I’ll plan it, ask before risky actions, and keep every step visible.'}], logs:[] };

function avatar(name, color){ return `<span class="avatar" style="--avatar:${color}">${name}</span>` }
function app(){ document.querySelector('#app').innerHTML = `
<div class="shell">
 <aside class="sidebar">
  <div class="brand"><div class="brand-mark">${icons.brain}</div><div><b>AEGIS</b><small>WORK OS</small></div></div>
  <div class="workspace"><div class="eyebrow">WORKSPACE</div><div class="select-workspace">Founder workspace <span>⌄</span></div></div>
  <nav>${[['Mission Control','home'],['Live Runs','mission'],['Agent Team','agents'],['Tool Library','tools'],['Memory','memory']].map(([x,i])=>`<button class="nav ${state.active===x?'active':''}" data-nav="${x}"><i>${icons[i]}</i>${x}${x==='Live Runs'?'<em>3</em>':''}</button>`).join('')}</nav>
  <div class="sidebar-bottom"><div class="eyebrow">SYSTEM</div><button class="nav" data-nav="Settings"><i>${icons.settings}</i>Settings</button><div class="health"><span class="pulse"></span><div><b>All systems operational</b><small>Local runtime · v0.8.4</small></div></div><div class="profile">${avatar('AK','#8f7aff')}<div><b>Aditya Kumar</b><small>Owner · Free plan</small></div><span class="more">•••</span></div></div>
 </aside>
 <main class="main"><header><div class="breadcrumbs"><span class="status-dot"></span><span>Mission Control</span><span>/</span><b>Today</b></div><div class="header-actions"><button class="icon-btn" id="search">⌕</button><button class="icon-btn" id="theme">◐</button><button class="icon-btn"><span class="bell">●</span>♧</button>${avatar('AK','#8f7aff')}</div></header>
  <section class="content"><div class="hero"><div><div class="kicker"><span class="live-dot"></span> AUTONOMOUS WORKSPACE</div><h1>Good morning, Aditya <span>✦</span></h1><p>What would you like to accomplish today?</p></div><div class="date-chip">MON, SEP 14 <b>2026</b></div></div>
  <section class="command-card"><div class="command-top"><div class="brain-orb"><span>✦</span></div><div><div class="eyebrow">COMMAND CENTER <span class="ready">● READY</span></div><h2>Describe an outcome. Aegis handles the rest.</h2><p>I’ll break down your goal, assemble the right agents and tools, then execute with your approval.</p></div></div><div class="composer"><textarea id="prompt" placeholder="e.g. Build a launch plan for my new design agency..." rows="1"></textarea><div class="composer-bar"><div class="chips"><button data-fill="Research my competitors and summarize the top opportunities">＋ Add context</button><button class="chip" data-fill="Research my competitors and summarize the top opportunities">⌕ Research</button><button class="chip" data-fill="Create a launch campaign with a landing page and social posts">◈ Build something</button></div><div class="compose-actions"><button class="voice ${state.voice?'on':''}" id="voice">${icons.mic}</button><button class="send" id="send">${icons.send}</button></div></div></div><div class="approval-note"><span>♢</span> You stay in control · Aegis will always ask before external actions, spending, or publishing</div></section>
  <div class="section-head"><div><h3>Active workspace</h3><p>See what your agents are thinking and doing in real time.</p></div><button class="text-btn" id="open-all">Open all <span>↗</span></button></div>
  <div class="dashboard-grid"><section class="panel run-panel"><div class="panel-head"><div><span class="live-label"><i></i> LIVE RUN</span><h3>${state.running?'Launch campaign · in progress':'No active mission'}</h3></div><button class="kebab">•••</button></div>${state.running?`<div class="run-progress"><div class="progress-label"><span>Building your launch system</span><b>64%</b></div><div class="progress"><i></i></div></div><div class="activity-list">${state.logs.map(x=>`<div class="activity"><span class="activity-icon ${x.kind}">${x.icon}</span><div><b>${x.title}</b><small>${x.detail}</small></div><span class="activity-status">${x.done?'✓':'…'}</span></div>`).join('')}</div><button class="panel-link" id="view-run">Open live workspace ↗</button>`:`<div class="empty-run"><div class="empty-icon">${icons.play}</div><b>Nothing running right now</b><span>Start a mission above and watch the workspace come alive.</span><button class="outline-btn" data-fill="Create a launch campaign with a landing page and social posts">Start a mission <span>↗</span></button></div>`}</section>
  <section class="panel agents-panel"><div class="panel-head"><div><span class="eyebrow">YOUR AGENT TEAM</span><h3>Specialists on standby</h3></div><button class="add-btn">＋</button></div><div class="agent-list"><div class="agent-row">${avatar('N','#4e8cff')}<div><b>Nova <span class="tag">PLANNER</span></b><small>Turns outcomes into executable plans</small></div><span class="online"></span></div><div class="agent-row">${avatar('R','#26c79a')}<div><b>Rook <span class="tag green">BUILDER</span></b><small>Writes, tests and ships software</small></div><span class="online"></span></div><div class="agent-row">${avatar('S','#f09b4d')}<div><b>Sage <span class="tag orange">RESEARCHER</span></b><small>Browses the web and synthesizes insight</small></div><span class="online"></span></div></div><button class="panel-link" data-nav="Agent Team">Manage agent team <span>↗</span></button></section></div>
  <div class="lower-grid"><section class="panel tools-panel"><div class="panel-head"><div><span class="eyebrow">CONNECTED TOOLS</span><h3>Tools Aegis can use</h3></div><button class="text-btn" data-nav="Tool Library">Manage <span>↗</span></button></div><div class="tool-grid"><div class="tool"><span class="tool-logo notion">N</span><div><b>Notion</b><small>Workspace</small></div><i>●</i></div><div class="tool"><span class="tool-logo github">◉</span><div><b>GitHub</b><small>Repositories</small></div><i>●</i></div><div class="tool"><span class="tool-logo browser">◎</span><div><b>Browser</b><small>Web access</small></div><i>●</i></div><div class="tool"><span class="tool-logo drive">△</span><div><b>Google Drive</b><small>Files & docs</small></div><i>●</i></div></div><div class="tool-foot"><span>+ 8 more available</span><button>Discover tools in this system ↗</button></div></section><section class="panel memory-panel"><div class="panel-head"><div><span class="eyebrow">LONG-TERM MEMORY</span><h3>What Aegis remembers</h3></div><button class="text-btn" data-nav="Memory">View memory <span>↗</span></button></div><div class="memory-card"><span class="memory-icon">◉</span><div><b>Aditya prefers free & open-source tools</b><small>Learned 2 hours ago · from conversation</small></div><button>•••</button></div><div class="memory-card"><span class="memory-icon purple">✦</span><div><b>Brand voice: clear, bold, human</b><small>Updated yesterday · project: Aegis</small></div><button>•••</button></div></section></div>
 </section></main>
 <div id="toast" class="toast"></div><div id="modal"></div>
</div>`; bind(); }
function bind(){ document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{state.active=b.dataset.nav; app(); toast(`${state.active} workspace opened`)}); document.querySelectorAll('[data-fill]').forEach(b=>b.onclick=()=>{document.querySelector('#prompt').value=b.dataset.fill; document.querySelector('#prompt').focus()}); document.querySelector('#send').onclick=run; document.querySelector('#prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();run()}}; document.querySelector('#voice').onclick=()=>{state.voice=!state.voice;app(); if(state.voice&&'speechSynthesis' in window){speechSynthesis.speak(new SpeechSynthesisUtterance('Voice input is ready. What would you like to accomplish?'))}}; document.querySelector('#search').onclick=()=>modal(`<div class="modal-card"><button class="close">×</button><div class="eyebrow">COMMAND SEARCH</div><h2>Find anything in Aegis</h2><input autofocus placeholder="Search missions, agents, tools or memory..."/><div class="search-hints">⌘ K to open anytime · Search is local and private</div></div>`); document.querySelector('#open-all')?.addEventListener('click',()=>toast('All workspace panels are already visible')); document.querySelector('#view-run')?.addEventListener('click',()=>toast('Live workspace opened')); }
async function run(){let p=document.querySelector('#prompt').value.trim();if(!p)return toast('Tell Aegis what outcome you want first');try{const response=await fetch('/api/missions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({prompt:p})});const mission=await response.json();if(!response.ok)throw new Error(mission.error||'Mission could not be created');state.running=true;state.logs=[{icon:'✦',kind:'purple',title:'Mission created from your goal',detail:'Waiting for approval · real runtime plan generated',done:true},...mission.tasks.map(t=>({icon:t.role==='researcher'?'⌕':t.role==='builder'?'⌘':'✓',kind:t.role==='researcher'?'orange':t.role==='builder'?'green':'purple',title:t.title,detail:`${t.role} · ${t.capabilities.join(', ')}`,done:false}))];app();setTimeout(()=>approvalModal(mission),150)}catch(error){toast(`Runtime unavailable: ${error.message}`)}}
function approvalModal(mission){modal(`<div class="modal-card approval"><button class="close">×</button><div class="approval-symbol">♢</div><div class="eyebrow">APPROVAL REQUIRED · MISSION ${mission.id.slice(0,8)}</div><h2>Approve this mission plan?</h2><p>Aegis has understood your goal and created a bounded plan. It will not pretend to execute anything until a real capability adapter is available.</p><div class="scope"><b>${mission.goal}</b>${mission.tasks.map(t=>`<span>→ ${t.title} · ${t.role}</span>`).join('')}<span>Risk: ${mission.approval.risk.toUpperCase()} · write/external adapters remain gated</span></div><div class="modal-actions"><button class="quiet close">Not now</button><button class="primary" id="approve">Approve plan <span>↗</span></button></div></div>`);document.querySelector('#approve')?.addEventListener('click',async()=>{const r=await fetch(`/api/missions/${mission.id}/approve`,{method:'POST'});const updated=await r.json();document.querySelector('#modal').innerHTML='';state.logs=updated.tasks.map(t=>({icon:t.state==='waiting_for_adapter'?'!':'✓',kind:t.state==='waiting_for_adapter'?'orange':'green',title:t.title,detail:t.state==='waiting_for_adapter'?'Blocked: adapter not configured':'Completed',done:t.state!=='waiting_for_adapter'}));app();toast('Mission is visible in the runtime — execution adapter required before work starts')})}
function modal(html){document.querySelector('#modal').innerHTML=`<div class="modal-backdrop">${html}</div>`;document.querySelectorAll('.close').forEach(x=>x.onclick=()=>document.querySelector('#modal').innerHTML='');document.querySelector('#approve')?.addEventListener('click',()=>{document.querySelector('#modal').innerHTML='';toast('Approved — Sage is browsing safely');});}
function toast(s){let t=document.querySelector('#toast');if(!t)return;t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
app();
